name: Release on Tag

on:
  push:
    tags:
      - "opendos-v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract tag name
        id: tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"

      - name: Get latest 5 commits
        id: changelog
        run: |
          LOG=$(git log -n 5 --pretty="* %s (%h)")
          echo "log<<EOF" >> "$GITHUB_OUTPUT"
          echo "$LOG" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Find previous release (if exists)
        id: previous
        run: |
          PREV_TAG=$(git tag --sort=-creatordate | grep "^opendos-v" | grep -v "${{ steps.tag.outputs.TAG_NAME }}" | head -n 1 || true)
          echo "PREV_TAG=$PREV_TAG" >> "$GITHUB_OUTPUT"

      - name: Get changelog link
        id: compare_url
        run: |
          if [ -n "${{ steps.previous.outputs.PREV_TAG }}" ]; then
            echo "url=https://github.com/${{ github.repository }}/compare/${{ steps.previous.outputs.PREV_TAG }}...${{ steps.tag.outputs.TAG_NAME }}" >> "$GITHUB_OUTPUT"
          else
            echo "url=https://github.com/${{ github.repository }}/commits/${{ steps.tag.outputs.TAG_NAME }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Find workflow run with artifact
        uses: actions/github-script@v7
        id: find_run
        with:
          result-encoding: json
          script: |
            const runs = await github.rest.actions.listWorkflowRunsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 20,
              status: 'success',
              event: 'push'
            });

            for (const run of runs.data.workflow_runs) {
              const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: run.id
              });

              const found = artifacts.data.artifacts.find(a => a.name === "opendos.img");
              if (found) {
                return {
                  artifact_id: found.id,
                  run_id: run.id
                };
              }
            }

            throw new Error("Artifact 'opendos.img' not found");

      - name: Download opendos.img artifact
        uses: actions/download-artifact@v4
        with:
          name: opendos.img
          path: ./artifact
          run-id: ${{ steps.find_run.outputs.run_id }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.TAG_NAME }}
          name: ${{ steps.tag.outputs.TAG_NAME }}
          body: |
            New release: **${{ steps.tag.outputs.TAG_NAME }}**

            ## Recent changes:
            ${{ steps.changelog.outputs.log }}

            [Full changelog](${{ steps.compare_url.outputs.url }})

          files: ./artifact/opendos.img
