name: Release on Tag

on:
  push:
    tags:
      - 'opendos-v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Print Pushed Tag
        run: echo "Pushed tag:${{ github.ref_name }}"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get repository info
        id: repo_info
        run: |
          echo "REPO=${{ github.repository }}" >> "$GITHUB_OUTPUT"
          echo "TAG=${{ github.ref_name }}" >> "$GITHUB_OUTPUT"

      - name: Find Latest Successful Artifact
        id: find_artifact
        uses: actions/github-script@v7
        with:
          script: |
            const runs = await github.rest.actions.listWorkflowRunsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              status: 'success',
              per_page: 20,
            });
            let found;
            for (const run of runs.data.workflow_runs) {
              const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: run.id,
              });
              found = artifacts.data.artifacts.find(a => a.name === 'opendos.img');
              if (found) {
                core.setOutput('run_id', run.id);
                core.setOutput('artifact_id', found.id);
                break;
              }
            }
            if (!found) {
              core.setFailed('No matching artifact (opendos.img) found in recent successful workflow runs');
            }

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          # The artifact must be published with this name in the build workflow
          name: opendos.img
          path: .
        # If you need to download from a different workflow, you must use the github-script approach

      - name: Unzip artifact (if zipped)
        run: |
          if [ -f opendos.img.zip ]; then
            unzip -o opendos.img.zip
          fi

      - name: Get changelog
        id: changelog
        run: |
          TAG=${{ steps.repo_info.outputs.TAG }}
          echo "Getting previous tag..."
          PREV_TAG=$(git tag --sort=-creatordate | grep 'opendos-v' | grep -v "^$TAG$" | head -n1)

          echo "Previous tag: $PREV_TAG"
          if [ -z "$PREV_TAG" ]; then
            COMMITS=$(git log -n 5 --pretty=format:"- %s")
            CHANGELOG_URL="${{ github.server_url }}/${{ github.repository }}/commits"
          else
            COMMITS=$(git log "$PREV_TAG..HEAD" -n 5 --pretty=format:"- %s")
            CHANGELOG_URL="${{ github.server_url }}/${{ github.repository }}/compare/$PREV_TAG...$TAG"
          fi

          {
            echo "CHANGELOG<<EOF"
            echo "$COMMITS"
            echo ""
            echo "Full changelog: $CHANGELOG_URL"
            echo "EOF"
          } >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.repo_info.outputs.TAG }}
          name: ${{ steps.repo_info.outputs.TAG }}
          body: ${{ steps.changelog.outputs.CHANGELOG }}
          files: |
            opendos.img
